#!/bin/sh

# xset r rate 200 50 &

xrandr --output HDMI1 --right-of eDP1
xrandr --output eDP1 --mode 1920x1080
xrandr --output HDMI1 --mode 1600x900
set-theme &
# xcompmgr -c -f -D 5
# picom -b --experimental-backends --animations
# picom -b --experimental-backends
picom -b
slstatus &
dunst &
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
