#!/bin/sh

set-theme
picom -b --experimental-backends
slstatus &
dunst &
libinput-gestures-setup restart &
unclutter -idle 5 -root &
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm 2> /dev/null
